### PR TITLE
CI setup for this repo

### PR DESCRIPTION
**Pull request by brainstorm**
Objective: Migrate `RELEASE.md` to `.travisci.yml`.

At this point in time, https://github.com/openpnp/opencv/issues/51 seems to be a blocker for further progress, see [this travisci log](https://travis-ci.org/github/brainstorm/opencv/builds/685032390#L12597).

This is needed to close the loop/work on OpenCV 4.3.x migration for [my aarch64/arm64 efforts]( https://github.com/CCHS-Melbourne/openpnp-kiosk) while also being potentially useful for all other targets (OSX, x86, win, etc...).

### CODE REVIEW

**Comment by brainstorm** [comment]
Hmm, I might have pullrequested against the wrong branch, sorry... anyway, @vonnieda , have a quick look at the `.travisyml` and let me know what you think, feel free to grab it directly and work on top of it, I see that you are working on similar issues so don't want to step on your toes ;)

**Comment by brainstorm** [comment]
Still not ready, but worth reviewing before it gets too big I reckon... let's rekindle and take this over the finish line. Builds happening over:

https://travis-ci.com/github/brainstorm/opencv/builds/197152334

For now...

**Comment by brainstorm** [comment]
@ohbus The scripts in this PR work against all targets except windows (OSX just times out on TravisCI but does build ok).

Could you please port my scripts over to GitHub actions? TravisCI has changed owners and there are only 10000 "credits" available per user, after that I guess it transitions to a paid service (/cc @vonnieda)... so time to switch to GitHub actions for good I reckon!

**Comment by vonnieda** [comment]
Thanks for your work on this @brainstorm. I borrowed heavily from your work on the new Github Actions setup.

**Comment by brainstorm** [comment]
My pleasure! 👍🏻 Testing the generated docker container now ;)

**Pull request closed without merging**
