### PR TITLE
Check for several error fragments

### PR DESCRIPTION
**Pull request by weebl2000**
Not all class laoders return the same message, which was causing issues
for me.

### CODE REVIEW

**Comment by weebl2000** [comment]
For me calling OpenCV.loadShared() was causing issues. The errorFragment did not match the error this specific class loader throws. See screenshot. This was preventing loading the native library inside the jar.

**Comment by weebl2000** [comment]
image (1)

**Comment by vonnieda** [comment]
Looks good to me. I think this fixes #45 as well.

**Comment by vonnieda** [comment]
This is now included in release 4.3.0-2

**Pull request merged**
