### PR TITLE
Add arm 32 bit build

### PR DESCRIPTION
**Pull request by falkena**
Hello,

i added arm 32 bit build, since most of Raspberry Pi users (including me) still have 32 bit OS. Meanwhile, there is an 64 bit beta available, but i think it will take time to get a rid of 32 bit OS. May be it's of interest.

Signed-off-by: Alexander Falkenstern <alexander.falkenstern@gmail.com>

### CODE REVIEW

**Comment by vonnieda** [comment]
Looks good @falkena - but why did you change the JDK versions in the other steps? I probably should have added comments to make sure it was clear, but I use 8 in most cases to ensure that there are no class version issues when users deploy on an older VM.

**Comment by falkena** [comment]
> 
> 
> Looks good @falkena - but why did you change the JDK versions in the other steps? I probably should have added comments to make sure it was clear, but I use 8 in most cases to ensure that there are no class version issues when users deploy on an older VM.

Ok. The reason was to go to java 11, since more and more projects use java 11. I took a look, the longest support provide Azul till begin 2025. Other companies stop it in 2023. And most Linux platforms i know use java 11 as default. I have no issues to change it back to 8. Strange, CI failes in test step. Any clue why?

**Comment by vonnieda** [comment]
Looks like it was failing because the ARMv7 directory did not exist. Fixed in https://github.com/openpnp/opencv/actions/runs/658111923. I'll merge this tonight.

**Comment by vonnieda** [comment]
Merged - will tag and release soon. Thanks @falkena!

**Comment by falkena** [comment]
Thanks for merging and releasing @vonnieda :-)

**Pull request merged**
