### PR TITLE
Introduced CI using GitHub Actions

### LINKED ISSUE #58: Add Continuous Integration
Add workflow for CI using Jenkins or GitHub Actions to automate stuffs.

### PR DESCRIPTION
**Pull request by ohbus**
This PR resolves #58 

The Continuous Integration Tests are performed on the following 8 platforms:

- [x] macos-latest on x86_32-apple-darwin
- [x] macos-latest on x86_64-apple-darwin
- [x] ubuntu-18.04 on x86_64-armv7-linux
- [x] ubuntu-18.04 on x86_64-amd64-linux
- [x] ubuntu-18.04 on x86_32-amd64-linux
- [x] ubuntu-16.04 on x86_64-amd64-linux
- [x] ubuntu-20.04 on x86_64-amd64-linux
- [x] windows-2019 on x86_64-amd64-windows

You can refer to the results of these CI results from [here](https://github.com/ohbus/opencv/actions/runs/146558459)

### CODE REVIEW

**Comment by ohbus** [comment]
@vonnieda would you please have a look at this and suggest some improvements if needed.

Thank You.

**Comment by vonnieda** [comment]
Hi @ohbus - thanks for your PR, but I do have a few questions:

1. Is this intended to replace or augment the existing Travis CI script?
2. I don't know Github Actions well yet, so forgive me if I'm mistaken, but this essentially just builds the jar on a variety of platforms, right? It doesn't actually built opencv?

Thanks,
Jason

**Comment by brainstorm** [comment]
@vonnieda It should replace the existing TravisCI and it doesn't seem to build OpenCV.
@ohbus Did you check https://github.com/openpnp/opencv/pull/56 ? It's almost there except the windows build... we could either scrap TravisCI entirely and migrate the bits over from my draft PR over here or just push the last mile on TravisCI (where @vonnieda is a bit more used to I reckon?).

**Comment by ohbus** [comment]
> Hi @ohbus - thanks for your PR, but I do have a few questions:
> 
> 1. Is this intended to replace or augment the existing Travis CI script?
> 2. I don't know Github Actions well yet, so forgive me if I'm mistaken, but this essentially just builds the jar on a variety of platforms, right? It doesn't actually built opencv?
> 
> Thanks,
> Jason

1. @vonnieda I believe it will replace the existing Travis CI build
2. I think I really missed the part of not building the Open CV and only building the jars. Can you please show me a guide to do that as well. It will really be very helpful to me.

**Comment by ohbus** [comment]
> @vonnieda It should replace the existing TravisCI and it doesn't seem to build OpenCV.
> @ohbus Did you check #56 ? It's almost there except the windows build... we could either scrap TravisCI entirely and migrate the bits over from my draft PR over here or just push the last mile on TravisCI (where @vonnieda is a bit more used to I reckon?).

Yes please @brainstorm can you please help guide me on the part of how to generate the Open CV binaries for different platforms so that I can publish them after build

I was also thinking of augmenting it with a release.yml file to do releases automatically and also include the platform binaries in it. Help is always appreciated.

**Comment by brainstorm** [comment]
Check out my WIP PR and borrow the shell scripts ;)

**Comment by brainstorm** [comment]
@ohbus, in a nutshell here are the steps to copy/follow:

1. https://github.com/openpnp/opencv/pull/56/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R95
2. https://github.com/openpnp/opencv/pull/56/files#diff-0f42fd993ce699d1eaf4007157dd696e37a4ad3f424642cf0e504cfba2faa97e
3. https://github.com/openpnp/opencv/pull/56/files#diff-8efe1e6e8db6cbefb6fe2f43ec1d7a78b67235953d024956691ce8442931e1a2

In essence I just followed the RELEASE.md steps, scripting them... it's only Windows being tricky at this point, I'm not an expert on that platform.

@vonnieda, would you accept CI that doesn't build for windows?

**Comment by ohbus** [comment]
> @ohbus, in a nutshell here are the steps to copy/follow:
> 
> 1. https://github.com/openpnp/opencv/pull/56/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R95
> 2. https://github.com/openpnp/opencv/pull/56/files#diff-0f42fd993ce699d1eaf4007157dd696e37a4ad3f424642cf0e504cfba2faa97e
> 3. https://github.com/openpnp/opencv/pull/56/files#diff-8efe1e6e8db6cbefb6fe2f43ec1d7a78b67235953d024956691ce8442931e1a2
> 
> In essence I just followed the RELEASE.md steps, scripting them... it's only Windows being tricky at this point, I'm not an expert on that platform.
> 
> @vonnieda, would you accept CI that doesn't build for windows?

I am extremely sorry for being late to reply on this since I am on a vacation. And I also apologise for not being able to build the OpenCV module as I have not clearly read the instructions in the module and did the job in a jiffy which should never have been done.

I will start working on making this thing work using GitHub actions. I will keep you guys posted.

Does drafted PR triggers CI?

**Comment by brainstorm** [comment]
> Does drafted PR triggers CI?

@vonnieda, can you check settings under https://github.com/openpnp/opencv/settings/actions and make sure GitHub Actions are enabled?:

Skärmavbild 2020-12-01 kl  01 45 58

**Comment by vonnieda** [comment]
Checked, seems to be enabled:

Screen Shot 2020-12-02 at 9 04 51 PM

**Comment by brainstorm** [comment]
@ohbus Did you try to setup GHA on your fork? Does it work?

**Comment by ohbus** [comment]
> @ohbus Did you try to setup GHA on your fork? Does it work?

Sorry for the delay, I have been keeping a little busy.

Lets try wrapping it as quickly as I can in the coming weeks.

**Comment by ohbus** [comment]
I will discard this PR and start fresh.

**Comment by brainstorm** [comment]
Cool @ohbus, feel free to ask me any questions about the scripts I migrated/wrote on PR #56 💪🏻

**Comment by vonnieda** [comment]
Hi @brainstorm and @ohbus: I started working on this a bit last night and I'm going to try to finish it up this evening. 

Current work is here: https://github.com/openpnp/opencv/blob/feature/github-actions/.github/workflows/build_natives.yml

Builds are here: https://github.com/openpnp/opencv/actions

First goal is to get Linux (x64), Mac, and Windows working essentially how they work now, except automated. With that finished, and being able to do automatic releases, we'll have a good starting point if someone wants to add in logic for ARM.

Thanks,
Jason

**Pull request closed without merging**
